[versions]
jna = "5.5.0"
jxlayer = "3.0.4"
swingx = "1.6.1"
miglayout = "5.2"
svgSalamander = "1.1.2.4"
rsyntaxtextarea = "3.1.1"
junit = "5.6.2"
autoservice = "1.0-rc7"
lGoodDatePicker = "11.0.2"
swingDsl = "0.1.2"
nullabilityAnnotations = "16.0.2"
macOSFramework = "latest.release"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jxlayer = { module = "org.swinglabs:jxlayer", version.ref = "jxlayer" }
swingx = { module = "org.swinglabs:swingx", version.ref = "swingx" }
svgSalamander = { module = "com.formdev:svgSalamander", version.ref = "svgSalamander" }
swingDslLafSupport = { module = "com.github.weisj:swing-extensions-laf-support", version.ref = "swingDsl" }
autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice" }
autoservice-processor = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }
nullabilityAnnotations = { module = "org.jetbrains:annotations", version.ref = "nullabilityAnnotations" }

# MacOS frameworks
macosLegacy-javaVM-base = { module = "dev.nokee.framework:JavaVM", version.ref = "macOSFramework" }
macosLegacy-javaVM-capability-javaNativeFoundation = { module = "JavaVM:JavaNativeFoundation", version.ref = "macOSFramework" }
macos-javaNativeFoundation = { module = "dev.nokee.framework:JavaNativeFoundation", version.ref = "macOSFramework" }
macos-appKit = { module = "dev.nokee.framework:AppKit", version.ref = "macOSFramework" }
macos-cocoa = { module = "dev.nokee.framework:Cocoa", version.ref = "macOSFramework" }

# Test libraries
test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-miglayout-core = { module = "com.miglayout:miglayout-core", version.ref = "miglayout" }
test-miglayout-swing = { module = "com.miglayout:miglayout-swing", version.ref = "miglayout" }
test-lGoodDatePicker = { module = "com.github.lgooddatepicker:LGoodDatePicker", version.ref = "lGoodDatePicker" }
test-rsyntaxtextarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "rsyntaxtextarea" }

[bundles]
test-miglayout = ["test-miglayout-core", "test-miglayout-swing"]
